### ISSUE TITLE
End point is not walkable

### ISSUE THREAD

**Issue by Celuni** [davecusatis/A-Star-Sharp#2]
Hey I really love your A* implementation, thanks you, it is very lightweight and exactly what I was looking for!

But I quickly found out that the end location is not ALWAYS set to walkable if your MapData sets it to not walkable.

Even tho you wanted the end locaton to be ALWAYS walkable judging by the code:
`Node end = new Node( new Vector2( (int)( End.X / Node.NODE_SIZE ), (int)( End.Y / Node.NODE_SIZE ) ), true );`
but you actually did not implement an override to make sure that it is actually walkable.
`if ( !ClosedList.Contains( n ) && n.Walkable )`

that means if my MapData says the NPC is not walkable because he has collision obviously,
it won't find a path.

To get around this I would need to know the end position before I define my MapData and set the end location to walkable, but what I'm looking for is only defining the MapData once without knowing the end location so I don't have to make a lot of different MapDatas just so I can find another location on the same map.

- Can you please add a check/bool that make sure that the end is set to always walkable even if in you MapData it is not?

I know that in most cases you want to know if the end is actually reachable but in my case I know already that the end is always walkable, but I don't want to make thousands of new MapDatas just to overwrite the collison, I mean I'm doing that right now and it is turbo slow..

**Comment by Celuni** [comment]
I basicly mean this:
`if ( !ClosedList.Contains( n ) && ( n.Walkable || ( n.Position.X == end.Position.X & n.Position.Y == end.Position.Y ) ) )`

It's up to you if you need that, it could be handled via a bool to toggle this feature.

**Comment by davecusatis** [comment]
hey i don't have any plans to make any of these changes at this time, but feel free to open a pull request with the changes you would like, happy to merge it

**Comment by Celuni** [comment]
It is fine, I just want that others know about this.

I understand that for speed purposes it is important to do as little compares as possible but on a small map it isn't really impacting that much.
